
# This is a basic workflow to help you get started with Actions

name: Check for prettier
# Controls when the workflow will run
on:
  pull_request:
    branches: [main, add-icon]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prettier:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      - name: Check prettier
        run: npm run check
  eslint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      - name: Check ESLint
        run: npm run eslint
